// <auto-generated />
using System;
using CodeReviewerAgent.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeReviewerAgent.Infra.Migrations
{
    [DbContext(typeof(CodeReviewDbContext))]
    [Migration("20260916220002_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeReviewerAgent.Core.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscardedFindings")
                        .HasColumnType("integer");

                    b.Property<string>("Engine")
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<int?>("RunId")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("RunId");

                    b.ToTable("Assessment", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Actionability")
                        .HasColumnType("integer");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("Calibration")
                        .HasColumnType("integer");

                    b.Property<int>("Correctness")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("JudgeModel")
                        .HasColumnType("text");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<string>("RubricVersion")
                        .HasColumnType("text");

                    b.Property<int>("SignalToNoise")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Evaluation", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Finding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("CodeSnippet")
                        .HasColumnType("text")
                        .HasJsonPropertyName("code_snippet");

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<int?>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Problem")
                        .HasColumnType("text");

                    b.Property<int?>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Suggestion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Finding", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.GoldenCaseScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CleanRounds")
                        .HasColumnType("integer");

                    b.Property<int>("DiscardedFindings")
                        .HasColumnType("integer");

                    b.Property<int>("ExactCalibrations")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("PrecisionCorrect")
                        .HasColumnType("integer");

                    b.Property<int>("PrecisionCounted")
                        .HasColumnType("integer");

                    b.Property<int>("RunId")
                        .HasColumnType("integer");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<int>("Successes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "CaseName")
                        .IsUnique();

                    b.ToTable("GoldenCaseResult", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.GoldenGate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Part")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("RunId")
                        .HasColumnType("integer");

                    b.Property<int>("Whole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Name")
                        .IsUnique();

                    b.ToTable("GoldenGate", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.GoldenRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Engine")
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<long>("LatencyP50Ms")
                        .HasColumnType("bigint");

                    b.Property<long>("LatencyP95Ms")
                        .HasColumnType("bigint");

                    b.Property<long>("LatencyP99Ms")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text");

                    b.Property<string>("ReportFile")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Model", "Skills", "PromptVersion", "StartedAt");

                    b.ToTable("GoldenRun", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Folder")
                        .IsUnique();

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ContentHash");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Assessment", b =>
                {
                    b.HasOne("CodeReviewerAgent.Core.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeReviewerAgent.Core.GoldenRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Evaluation", b =>
                {
                    b.HasOne("CodeReviewerAgent.Core.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Finding", b =>
                {
                    b.HasOne("CodeReviewerAgent.Core.Assessment", null)
                        .WithMany("Findings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.GoldenCaseScore", b =>
                {
                    b.HasOne("CodeReviewerAgent.Core.GoldenRun", null)
                        .WithMany("Cases")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.GoldenGate", b =>
                {
                    b.HasOne("CodeReviewerAgent.Core.GoldenRun", null)
                        .WithMany("Gates")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Review", b =>
                {
                    b.HasOne("CodeReviewerAgent.Core.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.Assessment", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("CodeReviewerAgent.Core.GoldenRun", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Gates");
                });
#pragma warning restore 612, 618
        }
    }
}
